version: '2'
services:
  db:
    image: postgres
    container_name: psql
    environment:
      POSTGRES_DB: gorm
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: yatuhashi-api
    expose:
      - 5432
  api:
    build:
      context: ./AiCompServer
      args:
        DBHOST: db
        HOST : 0.0.0.0
    container_name: aicomp
    environment:
      DBHOST: db
      HOST: 0.0.0.0
    command: ["./run.sh"]
    ports:
      - 9900:9000
    depends_on:
      - db
    links:
      - db
