version: '2'
services:
  db:
    image: postgres
    container_name: psql
    environment:
      POSTGRES_DB: gorm
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: yatuhashi-api
    expose:
      - 5432
  apiimage:
    build:
      context: ./AiCompServer
      dockerfile: Imagefile
    image: aicompimage:1.0
  redis:
    image: redis:3.2.9
  api:
    build:
      context: ./AiCompServer
      dockerfile: Dockerfile
      args:
        DBHOST: db
        HOST : 0.0.0.0
        REDIS: redis:6379
    image: aicompapi:1.0
    container_name: aicomp
    volumes:
      - ./correct/:/correct/
    environment:
      DBHOST: db
      HOST: 0.0.0.0
      REDIS: redis
      ANSWERFILE: /correct/answer
    command: ["./run.sh"]
    ports:
      - 8080:9000
    depends_on:
      - db
      - redis
    links:
      - redis
